[package]
name = "nls-ls"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "nls"
path = "src/main.rs"

[dependencies]
clap_lex = "0.5.0"
ignore = "0.4.20"
libc = "0.2.147"
term_grid = "0.1.7"
terminal_size = "0.2.5"
unicode-width = "0.1.10"
log = "0.4.20"
env_logger = "0.10.0"

[profile.release]
opt-level = 3
strip = true
lto = true
codegen-units = 1
