complete -c nls -l color -d 'Flag to control when to use color for output' -r -f -a "{always	'Always use color for output',auto	'Color for output only if stdout is a tty',never	'Never use color for output'}"
complete -c nls -s I -l ignore-glob -d 'Ignore entries matching glob pattern' -r
complete -c nls -l max-depth -d 'Set the max depth to recurse into' -r
complete -c nls -l mode -d 'Set the mode format to be used in long format' -r -f -a "{native	'Use the platform default mode format',pwsh	'Use powershell mode format e.g. \'darhsl\'. This is the default on windows',rwx	'Use symbolic format e.g. \'drwxrwxrwx\'. This is the default on unix like platforms'}"
complete -c nls -l time -d 'Set timestamp to use for sorting by timestamp or/and listing in long format' -r -f -a "{accessed	'Use timestamp of when entry was last accessed (-u)',changed	'Use timestamp of when entry status was last changed (-c)',created	'Use timestamp of when entry was created',modified	'Use timestamp of when entry was last modified',atime	'Alias to \'accessed\'',ctime	'Alias to \'changed\'',btime	'Alias to \'created\'',mtime	'Alias to \'modified\''}"
complete -c nls -s a -l all -d 'Include hidden entries in listing'
complete -c nls -s A -l almost-all -d 'Like -a, --all but do not list implied . and .. entries'
complete -c nls -l allocated-bytes -d 'Use raw allocated size'
complete -c nls -s c -d 'Use timestamp of when entry status was last changed'
complete -c nls -s C -d 'List entries top-to-bottom in a grid'
complete -c nls -s d -l directory -d 'Do not list directory contents, instead list the directory itself'
complete -c nls -s F -l classify -d 'Append filetype indicator (either */=@|) to entry file names'
complete -c nls -s g -d 'Like -l but do not list the owner column'
complete -c nls -l gitignore -d 'Ignore files set in \'.gitignore\' files'
complete -c nls -s h -l human-readable -d 'Format size using factors of 1024 like 1.0K 200M 3.0G etc'
complete -c nls -s H -l dereference-command-line -d 'Use target information of symlinks passed as arguments on command line'
complete -c nls -l help -d 'Print help information'
complete -c nls -s i -l inode -d 'List entries along with their file inode number'
complete -c nls -l iec -d 'Format size using factors of 1024 like 1.0Ki 200Mi 3.0Gi etc'
complete -c nls -l ignore-file -d 'Ignore files set in \'.ignore\' files'
complete -c nls -s k -l kibibytes -d 'Use 1024 byte blocks for allocated size'
complete -c nls -s l -d 'List entries along with their metadata in long format'
complete -c nls -s L -l dereference -d 'Use target information when listing symlink entries'
complete -c nls -s n -l numeric-uid-gid -d 'Like -l but list the owner and group names as their respective uid and gid'
complete -c nls -s o -d 'Like -l but do not list the group column'
complete -c nls -s p -d 'Append filetype indicator / to directory entry file names'
complete -c nls -s r -l reverse -d 'Reverse sorting order'
complete -c nls -s R -l recursive -d 'Recurse into directories'
complete -c nls -s s -l size -d 'List entries along with their allocated size'
complete -c nls -s S -d 'Sort entries by largest size first'
complete -c nls -l si -d 'Format size using factors of 1000 like 1.0K 200M 3.0G etc'
complete -c nls -s t -d 'Sort entries by most recent timestamp first'
complete -c nls -s u -d 'Use timestamp of when entry was last accessed'
complete -c nls -l version -d 'Print version information'
complete -c nls -s x -d 'List entries left-to-right in a grid'
complete -c nls -s 1 -d 'List one entry per line'
